
package com.trabajouy.webservices;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "OfertaLaboralYaExisteException", targetNamespace = "http://webservices/")
public class OfertaLaboralYaExisteException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private OfertaLaboralYaExisteException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public OfertaLaboralYaExisteException_Exception(String message, OfertaLaboralYaExisteException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public OfertaLaboralYaExisteException_Exception(String message, OfertaLaboralYaExisteException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.trabajouy.webservices.OfertaLaboralYaExisteException
     */
    public OfertaLaboralYaExisteException getFaultInfo() {
        return faultInfo;
    }

}
