
package com.trabajouy.webservices;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "WebServicesIUsuario", targetNamespace = "http://webservices/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServicesIUsuario {


    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @param arg7
     * @throws FechaInvalidaException_Exception
     * @throws UsuarioRegistradoException_Exception
     */
    @WebMethod
    @Action(input = "http://webservices/WebServicesIUsuario/ingresarDatosPostulanteRequest", output = "http://webservices/WebServicesIUsuario/ingresarDatosPostulanteResponse", fault = {
        @FaultAction(className = UsuarioRegistradoException_Exception.class, value = "http://webservices/WebServicesIUsuario/ingresarDatosPostulante/Fault/UsuarioRegistradoException"),
        @FaultAction(className = FechaInvalidaException_Exception.class, value = "http://webservices/WebServicesIUsuario/ingresarDatosPostulante/Fault/FechaInvalidaException")
    })
    public void ingresarDatosPostulante(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        byte[] arg5,
        @WebParam(name = "arg6", partName = "arg6")
        String arg6,
        @WebParam(name = "arg7", partName = "arg7")
        String arg7)
        throws FechaInvalidaException_Exception, UsuarioRegistradoException_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @param arg7
     * @throws FechaInvalidaException_Exception
     * @throws UsuarioRegistradoException_Exception
     */
    @WebMethod
    @Action(input = "http://webservices/WebServicesIUsuario/ingresarDatosEmpresaRequest", output = "http://webservices/WebServicesIUsuario/ingresarDatosEmpresaResponse", fault = {
        @FaultAction(className = UsuarioRegistradoException_Exception.class, value = "http://webservices/WebServicesIUsuario/ingresarDatosEmpresa/Fault/UsuarioRegistradoException"),
        @FaultAction(className = FechaInvalidaException_Exception.class, value = "http://webservices/WebServicesIUsuario/ingresarDatosEmpresa/Fault/FechaInvalidaException")
    })
    public void ingresarDatosEmpresa(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        byte[] arg5,
        @WebParam(name = "arg6", partName = "arg6")
        String arg6,
        @WebParam(name = "arg7", partName = "arg7")
        String arg7)
        throws FechaInvalidaException_Exception, UsuarioRegistradoException_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @throws FechaInvalidaException_Exception
     * @throws PostulacionYaExisteException_Exception
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @Action(input = "http://webservices/WebServicesIUsuario/ingresarDatosPostulacionRequest", output = "http://webservices/WebServicesIUsuario/ingresarDatosPostulacionResponse", fault = {
        @FaultAction(className = PostulacionYaExisteException_Exception.class, value = "http://webservices/WebServicesIUsuario/ingresarDatosPostulacion/Fault/PostulacionYaExisteException"),
        @FaultAction(className = FechaInvalidaException_Exception.class, value = "http://webservices/WebServicesIUsuario/ingresarDatosPostulacion/Fault/FechaInvalidaException"),
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webservices/WebServicesIUsuario/ingresarDatosPostulacion/Fault/UsuarioNoExisteException")
    })
    public void ingresarDatosPostulacion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4)
        throws FechaInvalidaException_Exception, PostulacionYaExisteException_Exception, UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @return
     *     returns com.trabajouy.webservices.DtEmpresaArray
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServicesIUsuario/obtenerEmpresasRequest", output = "http://webservices/WebServicesIUsuario/obtenerEmpresasResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webservices/WebServicesIUsuario/obtenerEmpresas/Fault/UsuarioNoExisteException")
    })
    public DtEmpresaArray obtenerEmpresas()
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @return
     *     returns com.trabajouy.webservices.DtPostulanteArray
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServicesIUsuario/obtenerPostulantesRequest", output = "http://webservices/WebServicesIUsuario/obtenerPostulantesResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webservices/WebServicesIUsuario/obtenerPostulantes/Fault/UsuarioNoExisteException")
    })
    public DtPostulanteArray obtenerPostulantes()
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.trabajouy.webservices.DtEmpresa
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServicesIUsuario/obtenerEmpresaRequest", output = "http://webservices/WebServicesIUsuario/obtenerEmpresaResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webservices/WebServicesIUsuario/obtenerEmpresa/Fault/UsuarioNoExisteException")
    })
    public DtEmpresa obtenerEmpresa(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.trabajouy.webservices.DtUsuario
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServicesIUsuario/obtenerUsuarioRequest", output = "http://webservices/WebServicesIUsuario/obtenerUsuarioResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webservices/WebServicesIUsuario/obtenerUsuario/Fault/UsuarioNoExisteException")
    })
    public DtUsuario obtenerUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns boolean
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServicesIUsuario/existePostulacionRequest", output = "http://webservices/WebServicesIUsuario/existePostulacionResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webservices/WebServicesIUsuario/existePostulacion/Fault/UsuarioNoExisteException")
    })
    public boolean existePostulacion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.trabajouy.webservices.DtEmpresaArray
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServicesIUsuario/busquedaEmpresasRequest", output = "http://webservices/WebServicesIUsuario/busquedaEmpresasResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webservices/WebServicesIUsuario/busquedaEmpresas/Fault/UsuarioNoExisteException")
    })
    public DtEmpresaArray busquedaEmpresas(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @throws PaqueteYaCompradoException_Exception
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @Action(input = "http://webservices/WebServicesIUsuario/comprarPaqueteRequest", output = "http://webservices/WebServicesIUsuario/comprarPaqueteResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webservices/WebServicesIUsuario/comprarPaquete/Fault/UsuarioNoExisteException"),
        @FaultAction(className = PaqueteYaCompradoException_Exception.class, value = "http://webservices/WebServicesIUsuario/comprarPaquete/Fault/PaqueteYaCompradoException")
    })
    public void comprarPaquete(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws PaqueteYaCompradoException_Exception, UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns com.trabajouy.webservices.DtPostulacion
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServicesIUsuario/obtenerPostulacionRequest", output = "http://webservices/WebServicesIUsuario/obtenerPostulacionResponse")
    public DtPostulacion obtenerPostulacion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @throws FechaInvalidaException_Exception
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @Action(input = "http://webservices/WebServicesIUsuario/modificarPostulanteRequest", output = "http://webservices/WebServicesIUsuario/modificarPostulanteResponse", fault = {
        @FaultAction(className = FechaInvalidaException_Exception.class, value = "http://webservices/WebServicesIUsuario/modificarPostulante/Fault/FechaInvalidaException"),
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webservices/WebServicesIUsuario/modificarPostulante/Fault/UsuarioNoExisteException")
    })
    public void modificarPostulante(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        byte[] arg5)
        throws FechaInvalidaException_Exception, UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.trabajouy.webservices.DtEmpresa
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServicesIUsuario/obtenerEmpresaDadoOfertaRequest", output = "http://webservices/WebServicesIUsuario/obtenerEmpresaDadoOfertaResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webservices/WebServicesIUsuario/obtenerEmpresaDadoOferta/Fault/UsuarioNoExisteException")
    })
    public DtEmpresa obtenerEmpresaDadoOferta(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @throws FechaInvalidaException_Exception
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @Action(input = "http://webservices/WebServicesIUsuario/modificarEmpresaRequest", output = "http://webservices/WebServicesIUsuario/modificarEmpresaResponse", fault = {
        @FaultAction(className = FechaInvalidaException_Exception.class, value = "http://webservices/WebServicesIUsuario/modificarEmpresa/Fault/FechaInvalidaException"),
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webservices/WebServicesIUsuario/modificarEmpresa/Fault/UsuarioNoExisteException")
    })
    public void modificarEmpresa(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        byte[] arg5)
        throws FechaInvalidaException_Exception, UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.trabajouy.webservices.DtPostulante
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServicesIUsuario/obtenerPostulanteRequest", output = "http://webservices/WebServicesIUsuario/obtenerPostulanteResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webservices/WebServicesIUsuario/obtenerPostulante/Fault/UsuarioNoExisteException")
    })
    public DtPostulante obtenerPostulante(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServicesIUsuario/esEmpresaRequest", output = "http://webservices/WebServicesIUsuario/esEmpresaResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://webservices/WebServicesIUsuario/esEmpresa/Fault/UsuarioNoExisteException")
    })
    public boolean esEmpresa(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServicesIUsuario/healthCheckRequest", output = "http://webservices/WebServicesIUsuario/healthCheckResponse")
    public String healthCheck();

}
