
package com.trabajouy.webservices;

import java.io.IOException;
import java.io.InputStream;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Properties;
import java.io.FileInputStream;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "WebServicesIOfertaService", targetNamespace = "http://webservices/", wsdlLocation = "http://localhost:9132/oferta?wsdl")
public class WebServicesIOfertaService
    extends Service
{

    private final static URL WEBSERVICESIOFERTASERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICESIOFERTASERVICE_EXCEPTION;
    private final static QName WEBSERVICESIOFERTASERVICE_QNAME = new QName("http://webservices/", "WebServicesIOfertaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(obtenerURLDesdeConfiguracion()+"?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICESIOFERTASERVICE_WSDL_LOCATION = url;
        WEBSERVICESIOFERTASERVICE_EXCEPTION = e;
    }

    public WebServicesIOfertaService() {
        super(__getWsdlLocation(), WEBSERVICESIOFERTASERVICE_QNAME);
    }

    public WebServicesIOfertaService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICESIOFERTASERVICE_QNAME, features);
    }

    public WebServicesIOfertaService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICESIOFERTASERVICE_QNAME);
    }

    public WebServicesIOfertaService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICESIOFERTASERVICE_QNAME, features);
    }

    public WebServicesIOfertaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServicesIOfertaService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServicesIOferta
     */
    @WebEndpoint(name = "WebServicesIOfertaPort")
    public WebServicesIOferta getWebServicesIOfertaPort() {
        return super.getPort(new QName("http://webservices/", "WebServicesIOfertaPort"), WebServicesIOferta.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServicesIOferta
     */
    @WebEndpoint(name = "WebServicesIOfertaPort")
    public WebServicesIOferta getWebServicesIOfertaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices/", "WebServicesIOfertaPort"), WebServicesIOferta.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICESIOFERTASERVICE_EXCEPTION!= null) {
            throw WEBSERVICESIOFERTASERVICE_EXCEPTION;
        }
        return WEBSERVICESIOFERTASERVICE_WSDL_LOCATION;
    }
    
    @SuppressWarnings("unused")
	private static String obtenerURLDesdeConfiguracion() {
        Properties properties = new Properties();

        try (InputStream input = new FileInputStream("/ens/devel01/tpgr16/tpgr16/config.properties")) {
            if (input != null) {
                properties.load(input);
            } else {
                System.err.println("No se pudo cargar el archivo de configuración. FALLO SERVICE OFERTA");
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        String wsIP = properties.getProperty("ws_ip");
        String wsPort = properties.getProperty("ws_port");
        System.out.println(wsIP);

        return "http://" + wsIP + ":" + wsPort + "/oferta";
    }

}
